version: '3.9'

services:
  redis:
    image: redis:8.4-alpine
    container_name: slogi-ocr-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - slogi_ocr_network

  api:
    build: .
    container_name: sloger-ocr-api
    ports:
      - "127.0.0.1:8080:8080"
    restart: on-failure
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./app:/code/app
      - shared_temp:/tmp/file_processing
    command: ["fastapi", "run", "app/main.py", "--port", "8080"]
    networks:
      - slogi_ocr_network

  worker:
    build: .
    container_name: slogi-ocr-worker
    restart: on-failure
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./app:/code/app
      - shared_temp:/tmp/file_processing
    command: ["rq", "worker", "file_processing", "--url", "redis://redis:6379/0"]
    networks:
      - slogi_ocr_network

networks:
  slogi_ocr_network:
    driver: bridge

volumes:
  redis_data:
  shared_temp: